
# Your Wi-Fi SSID and password
wifi_ssid: "YourSsid"
wifi_password: "the_secrect_password"

# MQTT
mqtt_host: "192.168.1.175"
mqtt_user: "mqtt"
mqtt_pass: "your_mqtt_password"

# Ble Client display
ipixel_ble_mac: "3A:27:15:90:39:B2"